indy7:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

    extra_joints:
      - name: 'vacuum_gripper_joint'
        position: 0.0
    
  indy7_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
       - joint0
       - joint1
       - joint2
       - joint3
       - joint4
       - joint5
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        joint0: {trajectory: 0.1, goal: 0.1}
        joint1: {trajectory: 0.1, goal: 0.1}
        joint2: {trajectory: 0.1, goal: 0.1}
        joint3: {trajectory: 0.1, goal: 0.1}
        joint4: {trajectory: 0.1, goal: 0.1}
        joint5: {trajectory: 0.1, goal: 0.1}
    gains:
      joint0: {p: 550, d: 50, i: 10, i_clamp: 0}
      joint1: {p: 550, d: 150, i: 10, i_clamp: 0}
      joint2: {p: 250, d: 30, i: 5, i_clamp: 0}
      joint3: {p: 250, d: 30, i: 5, i_clamp: 0}
      joint4: {p: 150, d: 10, i: 5, i_clamp: 0}
      joint5: {p: 10, d: 1, i: 0, i_clamp: 0}
      stop_trajectory_duration: 0.5
      state_publish_rate:  25
      action_monitor_rate: 10
