/joint_state_controller:
  JointStateController:
    ros__parameters:
      type: "joint_state_controller/JointStateController"
      publish_rate:   50

/position_controllers:
  JointTrajectoryController:
    ros__parameters:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint0
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5

      gains:
        joint0:
          {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
        joint1:
          {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
        joint2:
          {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
        joint3:
          {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
        joint4:
          {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}
        joint5:
          {p: 100.0, i: 0.01, d:  10.0, i_clamp: 0}

/gazebo_ros_control: 
  pid_gains:
    ros__parameters:
      joint0:
        p: 100.0
        i: 0.01 
        d: 10.0
      joint1:
        p: 100.0
        i: 0.01 
        d: 10.0
      joint2:
        p: 100.0
        i: 0.01 
        d: 10.0
      joint3:
        p: 100.0
        i: 0.01 
        d: 10.0
      joint4:
        p: 100.0
        i: 0.01 
        d: 10.0            
      joint5:
        p: 100.0
        i: 0.01 
        d: 10.0      