# Publish all joint states
joint_state_controllers:
  type: joint_state_controller/JointStateController
  publish_rate: 50

  extra_joints:
    - name: 'vacuum_gripper_joint'
      position: 0.0

# indy7:
  # Position controllers
joint0_position_controller:
  type: position_controllers/JointPositionController
  joint: joint0
  # pid: {p : 100.0, i: 5.0, d: 80.0}

joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1
  # pid: {p : 100.0, i: 5.0, d: 80.0}

joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: joint2
  # pid: {p : 100.0, i: 5.0, d: 80.0}

joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: joint3
  # pid: {p : 100.0, i: 5.0, d: 80.0}

joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: joint4
  # pid: {p : 100.0, i: 5.0, d: 80.0}

joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: joint5
  # pid: {p : 100.0, i: 5.0, d: 80.0}
  